//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.6.3
//     from Assets/PlayerController.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerController: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerController()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerController"",
    ""maps"": [
        {
            ""name"": ""Character"",
            ""id"": ""bc391ebd-913c-4c92-91a9-fdf667cf112c"",
            ""actions"": [
                {
                    ""name"": ""Attack"",
                    ""type"": ""Button"",
                    ""id"": ""5c81ec49-50e0-407a-a87d-88796d85dd24"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Jump"",
                    ""type"": ""Button"",
                    ""id"": ""71ea53f0-9c1c-441e-b642-9c3c2aa917ad"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Dash"",
                    ""type"": ""Button"",
                    ""id"": ""85d3bc12-b19d-4d51-9ec6-fea55aeae273"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Slash"",
                    ""type"": ""Button"",
                    ""id"": ""5e44b29a-c625-4ceb-a8e1-9afca7f373ff"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""UI_Option"",
                    ""type"": ""Button"",
                    ""id"": ""5c0fcf0b-59b4-468e-ac70-c9fbac4c5e0f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""UI_Inventory"",
                    ""type"": ""Button"",
                    ""id"": ""f4509891-0883-48ea-a253-66eef1fc317c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""UI_Skilltree"",
                    ""type"": ""Button"",
                    ""id"": ""ba5a08db-d84c-4379-9ce8-37e86395cf68"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""QuickSlot01"",
                    ""type"": ""Button"",
                    ""id"": ""58642c19-98ef-41eb-9ae1-449ab447957e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""QuickSlot02"",
                    ""type"": ""Button"",
                    ""id"": ""4e979c31-f81a-4d16-bad8-0b28efd325e3"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""QuickSlot03"",
                    ""type"": ""Button"",
                    ""id"": ""ae6249c0-e90a-4815-a73a-157db4d27ccb"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""QuickSlot04"",
                    ""type"": ""Button"",
                    ""id"": ""148688d3-b17c-45a0-8b0c-87f51ef46cd4"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""QuickSlot05"",
                    ""type"": ""Button"",
                    ""id"": ""6fb52906-82fd-4e01-9ab8-c49866b884b8"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Up"",
                    ""type"": ""Button"",
                    ""id"": ""a3dfc479-2f7e-4d3f-953d-24b8292db051"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Down"",
                    ""type"": ""Value"",
                    ""id"": ""b423eb8e-7e18-4fe2-8b4e-87b628570fb2"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Left"",
                    ""type"": ""Button"",
                    ""id"": ""41934b84-3a1e-4596-a9c8-548e17fd8cee"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Right"",
                    ""type"": ""Button"",
                    ""id"": ""309bab29-fceb-40a2-a838-2fa613dee7fb"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""8d025fba-1472-49c8-acf4-663440bdaaef"",
                    ""path"": ""<Keyboard>/x"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Attack"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c19bf7c1-8db6-4d68-90f3-7cf6b78a2e5a"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Attack"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""893dea6b-b07b-4b29-a3c1-1f19459f7794"",
                    ""path"": ""<Keyboard>/c"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0bebef8f-f09a-46a6-8e45-ae93cb81222f"",
                    ""path"": ""<Keyboard>/z"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Dash"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6df230ce-d590-48ed-9866-46963b1dc8a6"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Slash"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e8568f1f-7d49-4a11-a6a4-ae92ecb8e2ea"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""UI_Option"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5eac4c34-673a-4702-be67-5719e9b90fba"",
                    ""path"": ""<Keyboard>/i"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""UI_Inventory"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""969b665f-832e-4a06-b02f-f85434839a74"",
                    ""path"": ""<Keyboard>/k"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""UI_Skilltree"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d78ee065-c55a-467d-8f91-0691f198e9fa"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""QuickSlot01"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""dd9d3f21-4ca7-4799-9294-2674220e0755"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""QuickSlot02"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""515849b1-34ca-42a8-b27e-b0236761ae27"",
                    ""path"": ""<Keyboard>/3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""QuickSlot03"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2fa30007-cd5c-483e-abc2-46fccd3f3464"",
                    ""path"": ""<Keyboard>/4"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""QuickSlot04"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""fdde2bfa-06a2-4b43-95d1-eba33b396476"",
                    ""path"": ""<Keyboard>/5"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""QuickSlot05"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d96c5c9f-c206-4410-90c9-dd65160f5997"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Up"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6e8e7a27-2836-4f92-99c3-6624bcd0afa1"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Down"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b56631ae-e099-4780-aea5-69dd6a3441f7"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Left"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""eb259016-d8d0-4a83-a0fe-a4c1693e8e22"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Right"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Character
        m_Character = asset.FindActionMap("Character", throwIfNotFound: true);
        m_Character_Attack = m_Character.FindAction("Attack", throwIfNotFound: true);
        m_Character_Jump = m_Character.FindAction("Jump", throwIfNotFound: true);
        m_Character_Dash = m_Character.FindAction("Dash", throwIfNotFound: true);
        m_Character_Slash = m_Character.FindAction("Slash", throwIfNotFound: true);
        m_Character_UI_Option = m_Character.FindAction("UI_Option", throwIfNotFound: true);
        m_Character_UI_Inventory = m_Character.FindAction("UI_Inventory", throwIfNotFound: true);
        m_Character_UI_Skilltree = m_Character.FindAction("UI_Skilltree", throwIfNotFound: true);
        m_Character_QuickSlot01 = m_Character.FindAction("QuickSlot01", throwIfNotFound: true);
        m_Character_QuickSlot02 = m_Character.FindAction("QuickSlot02", throwIfNotFound: true);
        m_Character_QuickSlot03 = m_Character.FindAction("QuickSlot03", throwIfNotFound: true);
        m_Character_QuickSlot04 = m_Character.FindAction("QuickSlot04", throwIfNotFound: true);
        m_Character_QuickSlot05 = m_Character.FindAction("QuickSlot05", throwIfNotFound: true);
        m_Character_Up = m_Character.FindAction("Up", throwIfNotFound: true);
        m_Character_Down = m_Character.FindAction("Down", throwIfNotFound: true);
        m_Character_Left = m_Character.FindAction("Left", throwIfNotFound: true);
        m_Character_Right = m_Character.FindAction("Right", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Character
    private readonly InputActionMap m_Character;
    private List<ICharacterActions> m_CharacterActionsCallbackInterfaces = new List<ICharacterActions>();
    private readonly InputAction m_Character_Attack;
    private readonly InputAction m_Character_Jump;
    private readonly InputAction m_Character_Dash;
    private readonly InputAction m_Character_Slash;
    private readonly InputAction m_Character_UI_Option;
    private readonly InputAction m_Character_UI_Inventory;
    private readonly InputAction m_Character_UI_Skilltree;
    private readonly InputAction m_Character_QuickSlot01;
    private readonly InputAction m_Character_QuickSlot02;
    private readonly InputAction m_Character_QuickSlot03;
    private readonly InputAction m_Character_QuickSlot04;
    private readonly InputAction m_Character_QuickSlot05;
    private readonly InputAction m_Character_Up;
    private readonly InputAction m_Character_Down;
    private readonly InputAction m_Character_Left;
    private readonly InputAction m_Character_Right;
    public struct CharacterActions
    {
        private @PlayerController m_Wrapper;
        public CharacterActions(@PlayerController wrapper) { m_Wrapper = wrapper; }
        public InputAction @Attack => m_Wrapper.m_Character_Attack;
        public InputAction @Jump => m_Wrapper.m_Character_Jump;
        public InputAction @Dash => m_Wrapper.m_Character_Dash;
        public InputAction @Slash => m_Wrapper.m_Character_Slash;
        public InputAction @UI_Option => m_Wrapper.m_Character_UI_Option;
        public InputAction @UI_Inventory => m_Wrapper.m_Character_UI_Inventory;
        public InputAction @UI_Skilltree => m_Wrapper.m_Character_UI_Skilltree;
        public InputAction @QuickSlot01 => m_Wrapper.m_Character_QuickSlot01;
        public InputAction @QuickSlot02 => m_Wrapper.m_Character_QuickSlot02;
        public InputAction @QuickSlot03 => m_Wrapper.m_Character_QuickSlot03;
        public InputAction @QuickSlot04 => m_Wrapper.m_Character_QuickSlot04;
        public InputAction @QuickSlot05 => m_Wrapper.m_Character_QuickSlot05;
        public InputAction @Up => m_Wrapper.m_Character_Up;
        public InputAction @Down => m_Wrapper.m_Character_Down;
        public InputAction @Left => m_Wrapper.m_Character_Left;
        public InputAction @Right => m_Wrapper.m_Character_Right;
        public InputActionMap Get() { return m_Wrapper.m_Character; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(CharacterActions set) { return set.Get(); }
        public void AddCallbacks(ICharacterActions instance)
        {
            if (instance == null || m_Wrapper.m_CharacterActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_CharacterActionsCallbackInterfaces.Add(instance);
            @Attack.started += instance.OnAttack;
            @Attack.performed += instance.OnAttack;
            @Attack.canceled += instance.OnAttack;
            @Jump.started += instance.OnJump;
            @Jump.performed += instance.OnJump;
            @Jump.canceled += instance.OnJump;
            @Dash.started += instance.OnDash;
            @Dash.performed += instance.OnDash;
            @Dash.canceled += instance.OnDash;
            @Slash.started += instance.OnSlash;
            @Slash.performed += instance.OnSlash;
            @Slash.canceled += instance.OnSlash;
            @UI_Option.started += instance.OnUI_Option;
            @UI_Option.performed += instance.OnUI_Option;
            @UI_Option.canceled += instance.OnUI_Option;
            @UI_Inventory.started += instance.OnUI_Inventory;
            @UI_Inventory.performed += instance.OnUI_Inventory;
            @UI_Inventory.canceled += instance.OnUI_Inventory;
            @UI_Skilltree.started += instance.OnUI_Skilltree;
            @UI_Skilltree.performed += instance.OnUI_Skilltree;
            @UI_Skilltree.canceled += instance.OnUI_Skilltree;
            @QuickSlot01.started += instance.OnQuickSlot01;
            @QuickSlot01.performed += instance.OnQuickSlot01;
            @QuickSlot01.canceled += instance.OnQuickSlot01;
            @QuickSlot02.started += instance.OnQuickSlot02;
            @QuickSlot02.performed += instance.OnQuickSlot02;
            @QuickSlot02.canceled += instance.OnQuickSlot02;
            @QuickSlot03.started += instance.OnQuickSlot03;
            @QuickSlot03.performed += instance.OnQuickSlot03;
            @QuickSlot03.canceled += instance.OnQuickSlot03;
            @QuickSlot04.started += instance.OnQuickSlot04;
            @QuickSlot04.performed += instance.OnQuickSlot04;
            @QuickSlot04.canceled += instance.OnQuickSlot04;
            @QuickSlot05.started += instance.OnQuickSlot05;
            @QuickSlot05.performed += instance.OnQuickSlot05;
            @QuickSlot05.canceled += instance.OnQuickSlot05;
            @Up.started += instance.OnUp;
            @Up.performed += instance.OnUp;
            @Up.canceled += instance.OnUp;
            @Down.started += instance.OnDown;
            @Down.performed += instance.OnDown;
            @Down.canceled += instance.OnDown;
            @Left.started += instance.OnLeft;
            @Left.performed += instance.OnLeft;
            @Left.canceled += instance.OnLeft;
            @Right.started += instance.OnRight;
            @Right.performed += instance.OnRight;
            @Right.canceled += instance.OnRight;
        }

        private void UnregisterCallbacks(ICharacterActions instance)
        {
            @Attack.started -= instance.OnAttack;
            @Attack.performed -= instance.OnAttack;
            @Attack.canceled -= instance.OnAttack;
            @Jump.started -= instance.OnJump;
            @Jump.performed -= instance.OnJump;
            @Jump.canceled -= instance.OnJump;
            @Dash.started -= instance.OnDash;
            @Dash.performed -= instance.OnDash;
            @Dash.canceled -= instance.OnDash;
            @Slash.started -= instance.OnSlash;
            @Slash.performed -= instance.OnSlash;
            @Slash.canceled -= instance.OnSlash;
            @UI_Option.started -= instance.OnUI_Option;
            @UI_Option.performed -= instance.OnUI_Option;
            @UI_Option.canceled -= instance.OnUI_Option;
            @UI_Inventory.started -= instance.OnUI_Inventory;
            @UI_Inventory.performed -= instance.OnUI_Inventory;
            @UI_Inventory.canceled -= instance.OnUI_Inventory;
            @UI_Skilltree.started -= instance.OnUI_Skilltree;
            @UI_Skilltree.performed -= instance.OnUI_Skilltree;
            @UI_Skilltree.canceled -= instance.OnUI_Skilltree;
            @QuickSlot01.started -= instance.OnQuickSlot01;
            @QuickSlot01.performed -= instance.OnQuickSlot01;
            @QuickSlot01.canceled -= instance.OnQuickSlot01;
            @QuickSlot02.started -= instance.OnQuickSlot02;
            @QuickSlot02.performed -= instance.OnQuickSlot02;
            @QuickSlot02.canceled -= instance.OnQuickSlot02;
            @QuickSlot03.started -= instance.OnQuickSlot03;
            @QuickSlot03.performed -= instance.OnQuickSlot03;
            @QuickSlot03.canceled -= instance.OnQuickSlot03;
            @QuickSlot04.started -= instance.OnQuickSlot04;
            @QuickSlot04.performed -= instance.OnQuickSlot04;
            @QuickSlot04.canceled -= instance.OnQuickSlot04;
            @QuickSlot05.started -= instance.OnQuickSlot05;
            @QuickSlot05.performed -= instance.OnQuickSlot05;
            @QuickSlot05.canceled -= instance.OnQuickSlot05;
            @Up.started -= instance.OnUp;
            @Up.performed -= instance.OnUp;
            @Up.canceled -= instance.OnUp;
            @Down.started -= instance.OnDown;
            @Down.performed -= instance.OnDown;
            @Down.canceled -= instance.OnDown;
            @Left.started -= instance.OnLeft;
            @Left.performed -= instance.OnLeft;
            @Left.canceled -= instance.OnLeft;
            @Right.started -= instance.OnRight;
            @Right.performed -= instance.OnRight;
            @Right.canceled -= instance.OnRight;
        }

        public void RemoveCallbacks(ICharacterActions instance)
        {
            if (m_Wrapper.m_CharacterActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(ICharacterActions instance)
        {
            foreach (var item in m_Wrapper.m_CharacterActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_CharacterActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public CharacterActions @Character => new CharacterActions(this);
    public interface ICharacterActions
    {
        void OnAttack(InputAction.CallbackContext context);
        void OnJump(InputAction.CallbackContext context);
        void OnDash(InputAction.CallbackContext context);
        void OnSlash(InputAction.CallbackContext context);
        void OnUI_Option(InputAction.CallbackContext context);
        void OnUI_Inventory(InputAction.CallbackContext context);
        void OnUI_Skilltree(InputAction.CallbackContext context);
        void OnQuickSlot01(InputAction.CallbackContext context);
        void OnQuickSlot02(InputAction.CallbackContext context);
        void OnQuickSlot03(InputAction.CallbackContext context);
        void OnQuickSlot04(InputAction.CallbackContext context);
        void OnQuickSlot05(InputAction.CallbackContext context);
        void OnUp(InputAction.CallbackContext context);
        void OnDown(InputAction.CallbackContext context);
        void OnLeft(InputAction.CallbackContext context);
        void OnRight(InputAction.CallbackContext context);
    }
}
